# Generated by Django 3.0.7 on 2020-06-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acousticness', models.IntegerField(default=0)),
                ('danceability', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
                ('instrumentalness', models.IntegerField(default=0)),
                ('key', models.IntegerField(default=0)),
                ('liveness', models.IntegerField(default=0)),
                ('loudness', models.IntegerField(default=0)),
                ('speechiness', models.IntegerField(default=0)),
                ('tempo', models.IntegerField(default=0)),
                ('time_signature', models.IntegerField(default=0)),
                ('valence', models.IntegerField(default=0)),
            ],
        ),
    ]
