# Generated by Django 3.0.7 on 2020-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='acousticness',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='danceability',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='energy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='instrumentalness',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='key',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='liveness',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='loudness',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='speechiness',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='tempo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='time_signature',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='valence',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
